

const a = 1;

try{

    a = 5;

}catch(err){

    console.log(err);
}